### PR TITLE
Prepare version 3.9.3

### PR DESCRIPTION
**Pull request by maxhelias**

### CODE REVIEW

**Comment by Nek-** [comment]
Maybe we could add the repeatable attribute to this release? https://github.com/odolbeau/phone-number-bundle/issues/146

**Review by Nek- — APPROVED** [review]

**Review by Nek- — CHANGES_REQUESTED** [review]

**Comment by maxhelias** [comment]
@Nek- If someone is working on it, yeah, we can actually wait a bit.

**Comment by odolbeau** [comment]
Could you please bump the `branch-alias` to `3.9.x-dev` in composer.json? :pray:

**Comment by maxhelias** [comment]
@odolbeau Done 😉

**Review by odolbeau — APPROVED** [review]

**Pull request merged**
