### PR TITLE
feat: make constraint repeatable

### PR DESCRIPTION
**Pull request by AlexOstrovsky**
Work for #146

### CODE REVIEW

**Review by maxhelias — APPROVED** [review]
Can you also add an entry in the CHANGELOG.md pls ?

**Comment by AlexOstrovsky** [comment]
@maxhelias added

**Comment by maxhelias** [comment]
Thanks for your contribution 👍

**Comment by AlexOstrovsky** [comment]
@maxhelias can you please publish a new release so this PR is there? thanks

**Comment by maxhelias** [comment]
You're right to call back, I'd forgotten, here's the release: https://github.com/odolbeau/phone-number-bundle/releases/tag/v3.10.1

**Pull request merged**
