### PR TITLE
Added twig filter for out-of-country dialing purposes

### PR DESCRIPTION
**Pull request by renzowebstack**

### CODE REVIEW

**Review by odolbeau — CHANGES_REQUESTED** [review]
Hi @renzowebstack & thanks for your contribution! :tada: 

I'd suggest to use `phone_number_format_out_of_country_calling_number` instead of  `phone_number_format_for_calling_from` (& same in the helper).
The name is a bit longer but is more consistent with the library.

+ we're missing some tests here. :)

**Comment by renzowebstack** [comment]
> Could you add some tests and squash your commits please?

Done, are the tests okay?

**Review by odolbeau — APPROVED** [review]

**Comment by odolbeau** [comment]
Thanks @renzowebstack!

**Comment by renzowebstack** [comment]
@odolbeau Is it possible that you can create a release for this?

**Pull request merged**
