### PR TITLE
Improve travis integration

### PR DESCRIPTION
**Pull request by maxhelias**

### CODE REVIEW

**Comment by Taluu** [comment]
We could use github actions + adding phpstan / psalm too while we're at it

**Comment by maxhelias** [comment]
I agree with PhpStan, but for GitHub Action I do not know.. Is it really worth it?

**Comment by Taluu** [comment]
It's awesome, and allow us to not depend on an external service (travis) which is known for its caveats...

**Comment by maxhelias** [comment]
I don't know Github Action, so please try it :D

**Comment by maxhelias** [comment]
So what are we doing? We close this, I leave you GitHub Action and I take care of phpstan ?

**Comment by Taluu** [comment]
As you wish, I'll try tomorrow. I will integrate it anyway

**Comment by maxhelias** [comment]
I just saw that there is already GitHub Actions for PhpStan / CSFixer 😅

**Comment by odolbeau** [comment]
Yeah, I already configured some Github actions. :)
I didn't see any PHP project using Github actions to run the test suite yet but feel free to play with it @Taluu 

Thanks for your PR @maxhelias!

**Comment by Taluu** [comment]
There's API Platform if you want an example. :}

**Pull request merged**
